spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JWT_Project
    username: root
    password: root
    #com.mysql.cj.jdbc.Driver'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=Project_JWT;encrypt=false
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto= update
#
#server.error.include-stacktrace=never
#server.error.include-message = always